/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WinrBtn {
        "loading": boolean;
        "type": 'primary' | 'secondary';
    }
    interface WinrInput {
        "label": string;
        "validable": boolean;
        "validator": string;
    }
    interface WinrModal {
        "caption": string;
        "hide": () => Promise<void>;
        "show": () => Promise<void>;
    }
}
declare global {
    interface HTMLWinrBtnElement extends Components.WinrBtn, HTMLStencilElement {
    }
    var HTMLWinrBtnElement: {
        prototype: HTMLWinrBtnElement;
        new (): HTMLWinrBtnElement;
    };
    interface HTMLWinrInputElement extends Components.WinrInput, HTMLStencilElement {
    }
    var HTMLWinrInputElement: {
        prototype: HTMLWinrInputElement;
        new (): HTMLWinrInputElement;
    };
    interface HTMLWinrModalElement extends Components.WinrModal, HTMLStencilElement {
    }
    var HTMLWinrModalElement: {
        prototype: HTMLWinrModalElement;
        new (): HTMLWinrModalElement;
    };
    interface HTMLElementTagNameMap {
        "winr-btn": HTMLWinrBtnElement;
        "winr-input": HTMLWinrInputElement;
        "winr-modal": HTMLWinrModalElement;
    }
}
declare namespace LocalJSX {
    interface WinrBtn {
        "loading"?: boolean;
        "type"?: 'primary' | 'secondary';
    }
    interface WinrInput {
        "label": string;
        "validable"?: boolean;
        "validator"?: string;
    }
    interface WinrModal {
        "caption"?: string;
        "onClosed"?: (event: CustomEvent<any>) => void;
        "onOpened"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "winr-btn": WinrBtn;
        "winr-input": WinrInput;
        "winr-modal": WinrModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "winr-btn": LocalJSX.WinrBtn & JSXBase.HTMLAttributes<HTMLWinrBtnElement>;
            "winr-input": LocalJSX.WinrInput & JSXBase.HTMLAttributes<HTMLWinrInputElement>;
            "winr-modal": LocalJSX.WinrModal & JSXBase.HTMLAttributes<HTMLWinrModalElement>;
        }
    }
}
